# Generated by Django 4.2.6 on 2023-10-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=50)),
                ('Project_Technologies', models.CharField(max_length=50)),
                ('Technical_Skillset_Frontend', models.CharField(max_length=50)),
                ('Technical_Skillset_Backend', models.CharField(max_length=50)),
                ('Technical_Skillset_Databases', models.CharField(max_length=50)),
                ('Technical_Skillset_Infrastructre', models.CharField(max_length=50)),
                ('Other_Information_Availability', models.CharField(max_length=100)),
            ],
        ),
    ]
